export const movieActionTypes = {
    SEARCH_SUCCESS:'SEARCH_MOVIE',
    MOVIE_SUCCESS:'MOVIE_SUCCES',
    ADD_SELECTED_GENRES:"ADD_SELECTED_GENRES",
    DELETE_SELECTED_GENRES:"DELETE_SELECTED_GENRES",
}
